global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'admin_service'
    static_configs:
      - targets: ['http://localhost:6969/']

  - job_name: 'collector_service'
    static_configs:
      - targets: ['collector_service:3001']

  - job_name: 'postgres'
    static_configs:
      - targets: ['pg:5432']
    metrics_path: /metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
